name: Pipeline
on:
  push:
    branches:
      - main
      - gh-actions

  pull_request:
    branches:
      - main
      - gh-actions

jobs:
  run-automated-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code/ Fetch code
        uses: actions/checkout@v3

      - name: Setup Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install node packages
        run: npm install

      - name: Restore database
        run: echo 'Restore database'

      - name: Start application
        run: echo 'Start application'

      - name: Run tests
        run: echo 'run tests'

      - name: Save test run artifacts
        run: echo 'Save test run artifacts'
